import Foundation
import UIKit

enum WarrantyEvidencePackBuilder {
    struct Input {
        let plan: WarrantyPlan
        let events: [WarrantyEvent]
        let documents: [DocumentRecord]
        let maintenanceRecords: [MaintenanceRecord]
        let faults: [FaultRecord]
    }

    static func buildPDF(input: Input) -> Data {
        let pageBounds = CGRect(x: 0, y: 0, width: 595, height: 842)
        let renderer = UIGraphicsPDFRenderer(bounds: pageBounds)
        let coverage = WarrantySupport.coverageStatusText(plan: input.plan)

        return renderer.pdfData { context in
            var y: CGFloat = 48
            let margin: CGFloat = 48
            let contentWidth = pageBounds.width - margin * 2

            func beginPageIfNeeded(requiredHeight: CGFloat) {
                if y + requiredHeight > pageBounds.height - margin {
                    context.beginPage()
                    y = margin
                }
            }

            func drawTitle(_ text: String) {
                beginPageIfNeeded(requiredHeight: 28)
                let attrs: [NSAttributedString.Key: Any] = [
                    .font: UIFont.boldSystemFont(ofSize: 20),
                    .foregroundColor: UIColor.label
                ]
                text.draw(at: CGPoint(x: margin, y: y), withAttributes: attrs)
                y += 28
            }

            func drawBody(_ text: String, bold: Bool = false) {
                let font = bold ? UIFont.boldSystemFont(ofSize: 12) : UIFont.systemFont(ofSize: 12)
                let paragraph = NSMutableParagraphStyle()
                paragraph.lineBreakMode = .byWordWrapping
                let attrs: [NSAttributedString.Key: Any] = [
                    .font: font,
                    .foregroundColor: UIColor.label,
                    .paragraphStyle: paragraph
                ]
                let rect = CGRect(x: margin, y: y, width: contentWidth, height: .greatestFiniteMagnitude)
                let measured = (text as NSString).boundingRect(
                    with: CGSize(width: contentWidth, height: .greatestFiniteMagnitude),
                    options: [.usesLineFragmentOrigin, .usesFontLeading],
                    attributes: attrs,
                    context: nil
                )
                beginPageIfNeeded(requiredHeight: measured.height + 8)
                (text as NSString).draw(
                    in: CGRect(x: margin, y: y, width: contentWidth, height: measured.height),
                    withAttributes: attrs
                )
                y += measured.height + 8
            }

            context.beginPage()
            drawTitle("Warranty Evidence Pack")
            drawBody("Generated by Lyneqo Caravan & Motorhome on \(Formatters.date(Date()))")
            drawBody("Vehicle warranty plan summary", bold: true)
            drawBody("Manufacturer: \(input.plan.manufacturer.isEmpty ? "Not recorded" : input.plan.manufacturer)")
            drawBody("Purchase date: \(Formatters.date(input.plan.purchaseDate))")
            drawBody("Coverage: \(coverage.title) — \(coverage.detail)")
            if !input.plan.warrantyType.isEmpty {
                drawBody("Warranty type: \(input.plan.warrantyType)")
            }
            if !input.plan.handbookNotes.isEmpty {
                drawBody("Handbook notes: \(input.plan.handbookNotes)")
            }

            drawBody("Service timeline", bold: true)
            if input.events.isEmpty {
                drawBody("No warranty events recorded.")
            } else {
                for event in input.events {
                    let status = WarrantySupport.statusDisplayName(
                        for: WarrantySupport.status(for: event, among: input.events)
                    )
                    let milestonePrefix = event.isImportantMilestone ? "! Important year · " : ""
                    var line = "\(milestonePrefix)\(event.displayTitle) · \(Formatters.date(event.scheduledDate)) · \(status)"
                    if let completed = event.completedDate {
                        line += " · Completed \(Formatters.date(completed))"
                    }
                    drawBody(line, bold: true)
                    if event.isImportantMilestone {
                        drawBody("Must complete on or before the purchase anniversary — no after-grace under typical published terms.")
                    }
                    drawBody(event.requirementText)
                    drawBody(WarrantySupport.windowSubtitle(for: event))
                }
            }

            drawBody("Linked documents", bold: true)
            let linkedDocs = WarrantySupport.warrantyDocuments(from: input.documents, events: input.events)
            let evidence = WarrantySupport.evidencePackAttachments(
                events: input.events,
                documents: input.documents,
                maintenanceRecords: input.maintenanceRecords,
                faults: input.faults
            )
            var listedFiles: [WarrantySupport.EvidencePackAttachment] = []
            var photographs: [(sourceTitle: String, displayName: String, image: UIImage)] = []
            for item in evidence {
                if item.isPhotograph, let image = MaintenanceAttachmentStore.loadImage(for: item.attachment) {
                    photographs.append((item.sourceTitle, item.displayName, image))
                } else {
                    listedFiles.append(item)
                }
            }
            if linkedDocs.isEmpty && listedFiles.isEmpty && photographs.isEmpty {
                drawBody("No warranty documents or event evidence recorded.")
            } else {
                for doc in linkedDocs {
                    drawBody("• \(doc.title.isEmpty ? doc.category.displayName : doc.title) · \(Formatters.date(doc.dateAdded))")
                }
                for item in listedFiles {
                    drawBody("• \(item.displayName) · attached to \(item.sourceTitle)")
                }
            }

            drawBody("Warranty items", bold: true)
            let warrantyItems = WarrantySupport.warrantyFaults(from: input.faults, events: input.events)
            if warrantyItems.isEmpty {
                drawBody("No warranty items recorded.")
            } else {
                for fault in warrantyItems {
                    drawBody("• \(fault.title.isEmpty ? "Item" : fault.title) · \(fault.status.displayName) · \(Formatters.date(fault.discoveredDate))")
                }
            }

            let repairs = WarrantySupport.warrantyRepairs(from: input.maintenanceRecords, events: input.events)
            if !repairs.isEmpty {
                drawBody("Related service records", bold: true)
                for repair in repairs {
                    drawBody("• \(repair.title.isEmpty ? repair.category.displayName : repair.title) · \(Formatters.date(repair.serviceDate))")
                }
            }

            if !photographs.isEmpty {
                drawBody("Photographs", bold: true)
                var lastSource: String?
                for item in photographs {
                    let maxHeight: CGFloat = 220
                    let scale = min(
                        contentWidth / max(item.image.size.width, 1),
                        maxHeight / max(item.image.size.height, 1)
                    )
                    let drawSize = CGSize(
                        width: item.image.size.width * scale,
                        height: item.image.size.height * scale
                    )
                    let sourceHeight: CGFloat = item.sourceTitle == lastSource ? 0 : 24
                    beginPageIfNeeded(requiredHeight: sourceHeight + drawSize.height + 36)
                    if item.sourceTitle != lastSource {
                        drawBody(item.sourceTitle, bold: true)
                        lastSource = item.sourceTitle
                    }
                    drawBody(item.displayName)
                    item.image.draw(in: CGRect(x: margin, y: y, width: drawSize.width, height: drawSize.height))
                    y += drawSize.height + 12
                }
            }

            beginPageIfNeeded(requiredHeight: 120)
            drawBody("Disclaimer", bold: true)
            drawBody(WarrantySupport.warrantyDisclaimer)
        }
    }

    static func photographItems(from input: Input) -> [(sourceTitle: String, displayName: String, image: UIImage)] {
        photographItems(
            from: WarrantySupport.evidencePackAttachments(
                events: input.events,
                documents: input.documents,
                maintenanceRecords: input.maintenanceRecords,
                faults: input.faults
            )
        )
    }

    static func photographItems(
        from attachments: [WarrantySupport.EvidencePackAttachment]
    ) -> [(sourceTitle: String, displayName: String, image: UIImage)] {
        attachments.compactMap { item in
            guard item.isPhotograph,
                  let image = MaintenanceAttachmentStore.loadImage(for: item.attachment) else {
                return nil
            }
            return (item.sourceTitle, item.displayName, image)
        }
    }
}
